### ISSUE TITLE
Please provide options to select from is coming

### ISSUE THREAD

**Issue by sourjyo0** [upmasked/number-verifier#1]
Every time I try to run it , this message keeps coming,what should I do?

**Comment by upmasked** [comment]
Please let us know what OS you are using.

I assume Windows, in that case, did you download number-verifier-v0.4-windows-amd64.zip, extract it, and run the .exe?

Thanks

**Comment by Tanmayshetty** [comment]
I am getting the same issue in **Ubuntu 18.04**.
I downloaded **number-verifier-v0.4-linux-amd64.tar.gz** and ran the executable with **./number-verifier**

**Comment by sourjyo0** [comment]
I used Windows 10  and extracted the zip file and ran the executable

**Comment by Inmanuel** [comment]
Hmmmm

**Comment by ShashikanthChill** [comment]
Same issue on windows 10. 
![image](https://user-images.githubusercontent.com/23189529/88915089-48126280-d281-11ea-9a62-908ec89a043d.png)

**Comment by upmasked** [comment]
This issue should be fixed in the latest release. Thanks for helping out.

If you're still experiencing this after updating, please create a new issue. Thanks!
