### ISSUE TITLE
Virtual or physical numbers?

### ISSUE THREAD

**Issue by transitive-bullshit** [upmasked/number-verifier#2]
Hey 👋 

I'm the author of [sms-number-verifier](https://github.com/transitive-bullshit/sms-number-verifier) and just came across this project + upmasked. Looks awesome 😄 

One of the main issues that I found with `smsreceivefree`, `twilio`, `plivo`, etc when I was building `sms-number-verifier` is that a lot of OTP providers reject virtual phone numbers (VOIP), so I ended up primarily using `getsmscode` which uses numbers associated with physical SIM cards presumably on a fleet of Android devices.

So my question is where on this spectrum does upmasked sit?

Thanks!

**Comment by upmasked** [comment]
Hello, nice project. Are you still updating your project?

Is `getsmscode` free or paid?

Currently we are also using virtual numbers. We're currently looking into getting physical numbers as well.
